services:
  backend:
    build: ./backend
    container_name: backend_dev
    volumes:
      - ./backend:/app
    ports:
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: 7hours_db
    ports:
      - "${MYSQL_PORT_DOCKER}:3306"
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: