services:
  backend:
    build: ./backend
    container_name: backend_dev
    volumes:
      - ./backend:/app
    ports:
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgis/postgis     # 👈 1. 이미지를 PostGIS로 변경
    container_name: 7hours_db_container # 👈 2. (선택) 이름 변경 (MySQL과 구분)
    ports:
      - "5432:5432"                 # 👈 3. 포트 변경 (MySQL 3306 -> PostGIS 5432)
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data # 👈 4. PostGIS 데이터 경로로 변경

volumes:
  db_data: