# Generated by Django 4.2.13 on 2025-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='user_eb73031a', max_length=50, unique=True, verbose_name='별명'),
        ),
    ]
