# Generated by Django 4.2.13 on 2025-11-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='user_0bb7338c', max_length=50, unique=True, verbose_name='별명'),
        ),
    ]
