# Generated by Django 4.2.13 on 2025-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='user_34884a64', max_length=50, unique=True, verbose_name='별명'),
        ),
    ]
