# Generated by Django 4.2.13 on 2025-11-19 08:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('kcisa_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ktour_content_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='세부 카테고리')),
            ],
            options={
                'verbose_name': '장소 통합 정보',
                'verbose_name_plural': '장소 통합 정보',
            },
        ),
    ]
