# Generated by Django 4.2.13 on 2025-11-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category3',
            name='parent',
        ),
        migrations.DeleteModel(
            name='KCISAPlace',
        ),
        migrations.RemoveField(
            model_name='koreatourplace',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='koreatourplace',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='koreatourplace',
            name='category3',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '장소 통합 정보', 'verbose_name_plural': '장소 통합 정보'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category3',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='세부 카테고리'),
        ),
        migrations.AddField(
            model_name='place',
            name='kcisa_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='ktour_content_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
        migrations.DeleteModel(
            name='KoreaTourPlace',
        ),
    ]
