# Generated by Django 4.2.13 on 2025-11-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_category2_parent_remove_category3_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ktour_content_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
