# Generated by Django 4.2.13 on 2025-11-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_ktour_content_id_alter_place_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ktour_content_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
