# Generated by Django 4.2.13 on 2025-11-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_delete_location_delete_place_delete_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('review', '산책후기'), ('info', '정보공유')], default='review', max_length=20),
        ),
    ]
