# Ollama 공식 이미지 사용
FROM ollama/ollama:latest

# 모델 미리 다운로드 (원하면)
# RUN ollama pull qwen2.5:7b
# docker exec -it ollama_server ollama pull qwen2.5:7b 이걸로 입력 

# RUN ollama pull llama3
# docker exec -it ollama_server ollama pull llama3 입력하면 됨 


# # 포트 노출
# EXPOSE 11434

# # 올바른 서버 실행 명령
# CMD ["/bin/ollama", "serve"]