# Generated by Django 4.2.13 on 2025-11-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='path_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
