# Generated by Django 4.2.13 on 2025-11-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
