# Generated by Django 4.2.13 on 2025-11-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_alter_path_path_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'ordering': ['-created_at']},
        ),
    ]
