# Generated by Django 4.2.13 on 2025-11-19 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paths', '0003_alter_path_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='source',
            field=models.CharField(choices=[('USER', '사용자 생성'), ('PUBLIC_API', '공공 API')], default='PUBLIC_API', max_length=20),
        ),
        migrations.AlterField(
            model_name='path',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
