# Generated by Django 4.2.13 on 2025-11-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, choices=[('M', '남아'), ('F', '여아')], default=None, max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('neutering', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '반려견',
                'verbose_name_plural': '반려견 목록',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종 목록',
                'db_table': 'pet_breed',
            },
        ),
        migrations.CreateModel(
            name='PetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=45)),
                ('event_title', models.CharField(blank=True, max_length=45, null=True)),
                ('event_date', models.DateTimeField()),
                ('next_due_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='pets.pet', verbose_name='반려견')),
            ],
            options={
                'verbose_name': '반려견 활동 기록',
                'db_table': 'pet_history',
            },
        ),
        migrations.CreateModel(
            name='PetCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateTimeField()),
                ('clinic_name', models.CharField(blank=True, max_length=45, null=True)),
                ('next_checkup_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pethistory', verbose_name='관련 기록')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='pets.pet', verbose_name='반려견')),
            ],
            options={
                'verbose_name': '반려견 검진 기록 상세',
                'db_table': 'pet_checkup',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petbreed', verbose_name='품종'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='집사'),
        ),
    ]
