# Generated by Django 4.2.13 on 2025-11-19 08:20

import core.custom_storages
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, choices=[('M', '남아'), ('F', '여아')], max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('neutering', models.BooleanField(default=False, help_text='중성화 수술 여부')),
                ('image', models.ImageField(blank=True, null=True, storage=core.custom_storages.PetsStorage(), upload_to=core.utils.UploadFilePathGenerator('profile'))),
            ],
            options={
                'verbose_name': '반려견',
                'verbose_name_plural': '반려견 목록',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=45, null=True, unique=True)),
                ('category', models.CharField(blank=True, help_text='소형견 / 중형견 / 대형견', max_length=20, null=True, verbose_name='분류')),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종 목록',
                'db_table': 'pet_breed',
                'ordering': ['category', 'breed_name'],
            },
        ),
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CHECKUP', '건강검진'), ('VACCINE', '예방접종'), ('FEED_PURCHASE', '사료구매')], default='CHECKUP', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet')),
            ],
            options={
                'verbose_name': '반려견 활동 기록',
                'verbose_name_plural': '반려견 활동 기록 목록',
                'db_table': 'pet_event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PetCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='pets.petevent')),
            ],
            options={
                'verbose_name': '반려견 검진 기록 상세',
                'verbose_name_plural': '반려견 검진 기록 상세 목록',
                'db_table': 'pet_event_checkup',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(help_text="반려견의 품종 이름(문자열)을 입력합니다. (예: '푸들').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petbreed', verbose_name='품종'),
        ),
    ]
