# Generated by Django 4.2.13 on 2025-11-10 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '활동 유형',
                'verbose_name_plural': '활동 유형 목록',
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, choices=[('M', '남아'), ('F', '여아')], default=None, max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('neutering', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '반려견',
                'verbose_name_plural': '반려견 목록',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종 목록',
                'db_table': 'pet_breed',
            },
        ),
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.eventtype')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet')),
            ],
            options={
                'verbose_name': '반려견 활동 기록',
                'verbose_name_plural': '반려견 활동 기록 목록',
                'db_table': 'pet_event',
            },
        ),
        migrations.CreateModel(
            name='PetCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_detail', to='pets.petevent')),
            ],
            options={
                'verbose_name': '반려견 검진 기록 상세',
                'verbose_name_plural': '반려견 검진 기록 상세 목록',
                'db_table': 'pet_event_checkup',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petbreed', verbose_name='품종'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='집사'),
        ),
    ]
