# Generated by Django 4.2.13 on 2025-11-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petbreed',
            options={'ordering': ['breed_name'], 'verbose_name': '품종', 'verbose_name_plural': '품종 목록'},
        ),
        migrations.AlterModelOptions(
            name='petevent',
            options={'ordering': ['-event_date'], 'verbose_name': '반려견 활동 기록', 'verbose_name_plural': '반려견 활동 기록 목록'},
        ),
        migrations.RemoveField(
            model_name='petbreed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='petbreed',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='petcheckup',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='petcheckup',
            name='event_date',
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남아'), ('F', '여아')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='neutering',
            field=models.BooleanField(default=False, help_text='중성화 수술 여부'),
        ),
        migrations.AlterField(
            model_name='petcheckup',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='pets.petevent'),
        ),
        migrations.AlterField(
            model_name='petevent',
            name='event_type',
            field=models.CharField(choices=[('CHECKUP', '건강검진'), ('VACCINE', '예방접종'), ('FEED_PURCHASE', '사료구매')], default='CHECKUP', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'created_at'], name='pet_owner_i_ef8fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['pet', 'event_date'], name='pet_event_pet_id_d14908_idx'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['pet', 'is_completed'], name='pet_event_pet_id_7c2b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['event_type', 'event_date'], name='pet_event_event_t_d6ee88_idx'),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
