# Generated by Django 4.2.13 on 2025-11-13 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.eventtype')),
            ],
            options={
                'verbose_name': '반려견 활동 기록',
                'db_table': 'pet_event',
            },
        ),
        migrations.RenameField(
            model_name='petcheckup',
            old_name='next_checkup_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='petcheckup',
            old_name='checkup_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='petcheckup',
            old_name='notes',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='petcheckup',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='petcheckup',
            name='history',
        ),
        migrations.RemoveField(
            model_name='petcheckup',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petbreed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petbreed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petcheckup',
            name='hospital_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petcheckup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='petcheckup',
            table='pet_event_checkup',
        ),
        migrations.DeleteModel(
            name='PetHistory',
        ),
        migrations.AddField(
            model_name='petevent',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petcheckup',
            name='event',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='checkup_detail', to='pets.petevent'),
            preserve_default=False,
        ),
    ]
