# Generated by Django 4.2.13 on 2025-11-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='집사'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['pet', 'event_date'], name='pet_event_pet_id_d14908_idx'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['pet', 'is_completed'], name='pet_event_pet_id_7c2b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='petevent',
            index=models.Index(fields=['event_type', 'event_date'], name='pet_event_event_t_d6ee88_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'created_at'], name='pet_owner_i_ef8fa5_idx'),
        ),
    ]
