# Generated by Django 4.2.13 on 2025-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_petbreed_options_alter_petevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbreed',
            name='category',
            field=models.CharField(blank=True, help_text='소형견 / 중형견 / 대형견', max_length=20, null=True, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='petbreed',
            name='breed_name',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
