# Generated by Django 4.2.13 on 2025-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_petbreed_category_alter_petbreed_breed_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petbreed',
            options={'ordering': ['category', 'breed_name'], 'verbose_name': '품종', 'verbose_name_plural': '품종 목록'},
        ),
    ]
