# Generated by Django 4.2.13 on 2025-11-18 02:19

import core.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petbreed_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.custom_storages.PetsStorage(), upload_to='profile'),
        ),
    ]
