# Generated by Django 4.2.13 on 2025-11-18 07:24

import core.custom_storages
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(help_text="반려견의 품종 이름(문자열)을 입력합니다. (예: '푸들').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petbreed', verbose_name='품종'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.custom_storages.PetsStorage(), upload_to=core.utils.UploadFilePathGenerator('profile')),
        ),
    ]
