# Generated by Django 4.2.13 on 2025-11-19 08:24

import core.custom_storages
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_breed_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.custom_storages.PetsStorage(), upload_to=core.utils.UploadFilePathGenerator('profile', user_field='owner')),
        ),
    ]
